---
alias: Startup - Load Zones
hide_entity: true
trigger:
  platform: homeassistant
  event: start
action:
  - service: input_select.set_options
    data:
      entity_id: input_select.waze_destination
      options: ["Home", "Sprint"]
